### ISSUE TITLE
advanced promtp enhancer: gpt works, groq and claude no

### ISSUE THREAD

**Issue by rafstahelin** [glibsonoran/Plush-for-ComfyUI#122]
I am getting gpt to work fine. i have environment variables setup in User Env variables. 
Have Groq free api and Claude paid. Not sure why it is not working. any troubleshooting available

HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 401 Unauthorized"
Executed {'node': '4', 'display_node': '4', 'output': {'text': ['Server was unable to process the request']}, 'prompt_id': '2e0cb4c6-9953-413f-8783-ce480d7b524c'}
Executed {'node': '2', 'display_node': '2', 'output': {'text': ['\n➤ Begin Log for: Advanced Prompt Enhancer, Node #34:\n✦ INFO: Converting Torch Tensor image to b64 Image file\n✦ ERROR: Authentication error: invalid x-api-key\n✦ ERROR: Server was unable to process this request.\n']}, 'prompt_id': '2e0cb4c6-9953-413f-8783-ce480d7b524c'}
Prompt executed in 0.69 seconds

**Comment by glibsonoran** [comment]
Well, the only thing I can tell you is that it's flagging your api key as invalid, that could be because of several possible reasons:

*   Your api key is actually invalid for reasons that would be known only to the service provider.
*    You didn't use the correct Env Variable for the service you want to use, see [table here](https://github.com/glibsonoran/Plush-for-ComfyUI?tab=readme-ov-file#requirements)
*    You entered the key value incorrectly, or you didn't spell the Env Variable name right.

These are the only issues I can think of off-hand.

**Comment by glibsonoran** [comment]
closed
