### ISSUE TITLE
How-to Save Good Prompts for Re-Use

### ISSUE THREAD

**Issue by rafstahelin** [glibsonoran/Plush-for-ComfyUI#123]
Been glossing over the prompt enhancer and Prompt-Image Eval nodes, and wondering if there is a good node to save a good prompt into txt for re-use, and a Load Prompt node that helps plucking it back out into a wf through a subfolder path (using custom paths to organise the prompts by project or Lora training). I'd love to play with good prompts the way one can with wildcards, except without the randomisation. Or at some point mixing your LLM enhanced prompts with Wildcards. I am really interested in automation of the prompt which is so very important for flux t5xxl hungry wf's. 
Thanks for the great work! Really enjoying

**Comment by glibsonoran** [comment]
I don't have a node to save and retrieve prompts per se.  I will say that the *Exif Wrangler* node in the /Utils section of Plush will extract a prompt from a ComfyUI image and allow you to save it in a file, along with several other parameters from your workflow.  But since there's no way to really distinguish prompts from other types of text in the workflow you might have to fiddle a bit with the min_prompt_len,  Alpha_char_pct and perhaps a filter term until you display only your prompt and no other long form text.

**Comment by glibsonoran** [comment]
Issue closed
