### ISSUE TITLE
Reload of ComfyUI frontend hangs at HTTP requests to OpenAI/Groq

### ISSUE THREAD

**Issue by Jonseed** [glibsonoran/Plush-for-ComfyUI#136]
Every time the frontend is reloaded in the browser, it takes several seconds for Plush to make HTTP requests to OpenAI/Groq (probably checking model lists?). This happens even if there is no workflow loaded that uses a Plush node. I wonder if these requests could be handled differently, so they don't hold up frontend reloading?

**Comment by glibsonoran** [comment]
As far as I'm aware ComfyUI initializes all nodes when you start the app.  There's really no hook in Comfy that I"m aware of, that allows me to go out at node load time and fetch data.  This is probably by design as the developers would expect you to only start the app up once per session.  If the nodes went out and fetched their data when you instantiated them then you'd see the lag every time you loaded a node.
Do you restart the app often during your sessions?  That seems like an unusual work pattern.

**Comment by glibsonoran** [comment]
If you know you're going to be working in a way that causes you to need to reload the app often, and you're not using Plush in the workflow, you could just go into the Environment Variables dialogue box and put a 'x' in front of 'GROQ_API_KEY'.  That way it would determine the key to be missing and not load the models.

**Comment by Jonseed** [comment]
I am working on new custom nodes, and so I have to restart and reload Comfy often.

I guess if I know I'm not going to be using Plush for a while I can just disable it in the ComfyUI Manager.

**Comment by glibsonoran** [comment]
You can cache your own models locally and avoid the http: get delay if you're really that concerned about it. Here's how: 

*   Make sure you're using the latest version of Plush 
* Put your Groq API key in the `LLM_KEY` environment variable  Then put an 'x' in front of the Groq environment variable name to disable it. 
* Open the text file 'opt_models.txt' and enter your model names, e.g.:  Groq::llama-3.1-70b.
* Save the text file and start ComfyUI.  You won't see any http:get run on startup since LLM_KEY is for keys applied to Services whose URL's aren't built-in. 
* Enter the URL for Groq in the 'LLM_URL' field and choose 'Local app (URL)' as the service.

**Comment by glibsonoran** [comment]
Closed
