### ISSUE TITLE
Invalid credentials (error 401) on OpenRouter

### ISSUE THREAD

**Issue by mbac** [glibsonoran/Plush-for-ComfyUI#156]
Hi!

I'm trying to use the OpenRouter API but I keep getting an invalid credentials error (401); I have set a `$LLM_KEY` env variable and I guess it's being used. However, the error message in the troubleshooting output doesn't show what is being sent to the server. Is there a way we can check the API call being made?

Thanks!

**Comment by glibsonoran** [comment]
I don't show your api key because everything that appears in the ComfyUI workflow gets included in the image metadata.   So anyone who had a copy of your image would be able to easily extract your api key.  

Are you still having issues?  

*   Make sure your key was copied correctly by checking the first 4 and last 4 characters
* Make sure your environment variable is named correctly `LLM_KEY` (there's no $)
* Make sure you are setting the correct URL endpoint for the type of *AI_Service* connection you're using:
  *   **OpenAI API Connection:** LLM_URL = https://openrouter.ai/api/v1
  *   **Direct Web Connection:** LLM_URL = https://openrouter.ai/api/v1/chat/completions

**Comment by mbac** [comment]
Mmmh… It works now, with no particular changes on my part. The only thing that's changed is that I trashed the RunPod it was running in and deployed a new one today. I had restarted ComfyUI multiple times during yesterday's tests--I wonder if a system reboot was necessary, and if so why… (Running on Ubuntu 22.04)

Thanks!

**Comment by glibsonoran** [comment]
I had another Linux user with the same issue, wouldn't register a new env variable without a reboot.  The instructions in the ReadMe do state that you should reboot the machine after setting the env variable.  But I guess it's easy to miss that, and Windows doesn't seem to require it.

Anyway, I'm gonna close this.  If you have any more issues, let me know.
