### ISSUE TITLE
gpt-4 not available?

### ISSUE THREAD

**Issue by JulianKingman** [glibsonoran/Plush-for-ComfyUI#81]
I've added a style prompt, but can't select gpt-4 from the list. Is this a known issue? Am I using the wrong node? Just added this today.
<img width="472" alt="Screenshot 2024-06-14 at 9 48 03 AM" src="https://github.com/glibsonoran/Plush-for-ComfyUI/assets/1566400/e98b7d28-cd65-4f82-9602-cdda1320b00e">

**Comment by glibsonoran** [comment]
Hmm.  Here's what the node does.  When you boot up ComfyUI the OpenAI API library goes out and talks to the OpenAI server and presents your API key.  It then requests a list of available models and stores them in the app.  When you start up the Style_Prompt node it then applies a filter to this list to show only those models that contain the string 'gpt' (because there are dozens of other models that are of no interest to Comfy Users).  Of course all the gpt-4 and gpt-4o models have the 'gpt' string in them.

I tried this just now and I get all the models including the gpt-4 & 4o models.  When I remove my key or make it invalid it just returns 'none' in the model list.  So this only thing I can think of is that you possibly have a free or lower priced key that only allows you access to the gpt-3.5 models.  

Is that possible?

**Comment by glibsonoran** [comment]
Closed

**Comment by J-Cott** [comment]
> So the only thing I can think of is that you possibly have a free or lower priced key that only allows you access to the gpt-3.5 models.

Yes that was correct, only GPT3 showed up for me tonight, until I put $10 ($5 is the minimum) onto my API account and then GPT4 Etc showed up after a restart of ComfyUI.

**Comment by glibsonoran** [comment]
Glad you got a full set of models :)
